name: Merging Rules
# NOTE - this workflow is synced automatically. 
# Edit the template in planning/templates/services/merging-rules.yml
on:
   # Run on pull requests into the #master branch
   pull_request:
      branches: [master]

permissions:
   contents: write
   pull-requests: write

jobs:
   call-e2e-tests:
      name: E2E Tests
      uses: ./.github/workflows/cypress-e2e-tests.yml
   call-dependabot-merge:
      name: Dependabot
      needs: call-e2e-tests
      if: ${{ github.actor == 'dependabot[bot]' }}
      uses: CruGlobal/.github/.github/workflows/dependabot-merge.yml@main
      secrets: 
         DEPENDABOT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
